### ISSUE TITLE
Hitting HA to often?

### ISSUE THREAD

**Issue by riskitforabiscuit1252** [markusressel/ESPHome-Smart-Scale#12]
Hi there, I love the code you wrote it’s genuinely brilliant and wanted to thank you. It really has revolutionised my set up. Please let me know if there’s anyway that I could buy you a coffee and donate!

I’m using it as a Bed Occupancy sensor and was just wondering with it being updated every 0.2s is it hitting HA too much/often? Especially overnight when we’re in bed/on the scale for hours? I’m just worried that it may cause problems but I equally don’t know enough about it to know if I actually will  so I may just be worried for no reason.

If it is a potential problem, how would you amend the code to slightly reduce the amount of time it updates HA, without screwing up the amazing auto tare functionality? 

I attempted to increase the update interval on the kilogram data being sent to Home Assistant but it didn’t change anything until I also increased the update interval of the raw data which seemed to confuse me as the raw data itself wasn’t at all being sent to Home Assistant. It also had an effect on the auto tare so I put it all back as to not ruining things as it was working perfectly for me before fiddling with things, hence me trying to find out if changing the update interval is even something I need to worry about doing at all

Out of interest is there anything else I should adapt in the code to make it more suitable to use under a Bed?

**Comment by markusressel** [comment]
Hey @riskitforabiscuit1252 thx for the kind words, I really appreciate it! :heart: 

The raw sensor value is automatically pushed to the "non-raw" sensor through the `sensor.template.publish` action. I also just recently learned that this kind of push action also triggers an update of the value on the home assistant side, which is why the `update_interval` of the "non-raw" sensor has recently been changed to `never`, see #10. So effectively, only the `update_interval` of the raw sensor (and the settings of its quantile filter) is relevant for update speed to home-assistant.

Updating the value that often is probably not really necessary in the case of a constant reading, however it should also not affect Home Assistant in any way. If the data is collected over a long time it might cause it to become slow, but in that case I would suggest to not keep this data for more than a week and you should be good.

About the auto-tare: In #3 I suggested to turn it off completely and just ignore the small drift that might occur. I think that this might be good enough for using at as bed occupancy sensor, where only the rough value is enough and the exact measurement is not that important.

If you don't want to disable it completely, you will have to reevaluate how the algorithm works, since it will always try to slowly offset the "non-raw" sensor value to approach 0 Kg, if the current weight is below 10 Kg (this is the assumption that currently no weight is applied to the scale, since humans usually weigh more than 10 Kg :sweat_smile: ). Reworking this is not that trivial though, and I don't think the effort needed for this are really worth it, due to the accuracy not being too important here.

Thinking about it now, you could also calibrate in such a way, that the weight of the bed is considered 0 Kg, and let the current algorithm do its thing. However this really depends on how much weight is added by f.ex. blankets and pillows, which might change when swapping them out or even just while changing the sheets / duvet cover / whatever, while on a smart scale, there is no weight difference at all for anything.

**Comment by markusressel** [comment]
Closing this for now due to inactivity. Feel free to reopen if needed!
