### ISSUE TITLE
Does this allow for constant readings?

### ISSUE THREAD

**Issue by daleyjem** [markusressel/ESPHome-Smart-Scale#3]
Looking for something that can do constant weight readings of a water cooler jug. Does this allow for that?

**Comment by markusressel** [comment]
Sure, but you might want to take a look at the auto-tare stuff since that might interfere with the measurement if the weight you are measuring is very small (below 10 Kg). I would suggest either removing it completely or modifying it to never actually run (f.ex. by setting the limit to a negative number).

**Comment by lalebarde** [comment]
@daleyjem , could you publish here your results and modifications please?
